### ISSUE TITLE
printf alway output to the *stederr*

### ISSUE THREAD

**Issue by xning** [procszoo/procszoo#39]
Hence we should use it when we want output to the *stdout*. We have to choose

1. wrap and use the  *sys.stdout.write* .
2. from the *__future__* module import the *print* func.

@vfreex We need such function wrappers because Python 2 and Python 3 is  incompatible. I think we need lib module in the procszoo, then  each *script* and *module* could import and use it. What do you think? I don't think it's good idea to add *six* module or other *2to3* module.

**Comment by xning** [comment]
We can rename *printf* to *warn*, and name the wrapper of *sys.stdout.write* printf.

**Comment by vfreex** [comment]
Maybe we should print lib debug messages using [logging](https://docs.python.org/3/library/logging.html)?
For executable modules, like richard_parker and my_init, just print to stderr or stdout.

**Comment by xning** [comment]
Yes, I think so. But seems import logging module need some time.

**Comment by xning** [comment]
For scripts like *richard_parker* and *mamaji* and *c_functions*, it's better suppose they are running   in some terminals, hence we can follow the UNIX style to do some good CLIs.

For the *zoopkeeper*, yes, we should use the *logging* module.

**Comment by xning** [comment]
Have replaced the printf function.
